language: node_js
sudo: false
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_script:
  - "cp config/config_sample.js config/config.js"
after_script:
  - ./node_modules/.bin/mocha -R mocha-lcov-reporter -r blanket > lcov.info
  - cat lcov.info | codeclimate
